config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'pages#home'
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "home" => "pages#home"
  resources :torneios
  resources :teams
  resources :jogadors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/jogador.rb
class Jogador < ApplicationRecord
  has_and_belongs_to_many  :team
  belongs_to :user
  validates_presence_of :Nome, message: "Preenchimento obrigatório"
  validates_presence_of :Nick_no_jogo, message: "Preenchimento obrigatório"
  validates_presence_of :Idade, message: "Preenchimento obrigatório"
  validates_uniqueness_of :Nome, message: "já cadastrado"
  validates_uniqueness_of :Nick_no_jogo, message: "já utilizado"



end

app/controllers/jogadors_controller.rb
class JogadorsController < ApplicationController
  before_action :set_jogador, only: [:show, :edit, :update, :destroy]

  # GET /jogadors
  # GET /jogadors.json
  def index
    @jogadors = Jogador.where("user_id ="+current_user.id.to_s)
  end

  # GET /jogadors/1
  # GET /jogadors/1.json
  def show
  end

  # GET /jogadors/new
  def new
    @jogador = Jogador.new
  end

  # GET /jogadors/1/edit
  def edit
  end

  # POST /jogadors
  # POST /jogadors.json
  def create
    @jogador = Jogador.new(jogador_params)
    @jogador.user_id = current_user.id if current_user

    respond_to do |format|
      if @jogador.save
        format.html { redirect_to @jogador, notice: 'Jogador was successfully created.' }
        format.json { render :show, status: :created, location: @jogador }
      else
        format.html { render :new }
        format.json { render json: @jogador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jogadors/1
  # PATCH/PUT /jogadors/1.json
  def update
    @jogador.user_id = current_user.id if current_user
    respond_to do |format|

      if @jogador.update(jogador_params)
        format.html { redirect_to @jogador, notice: 'Jogador was successfully updated.' }
        format.json { render :show, status: :ok, location: @jogador }
      else
        format.html { render :edit }
        format.json { render json: @jogador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jogadors/1
  # DELETE /jogadors/1.json
  def destroy
    @jogador.destroy
    respond_to do |format|
      format.html { redirect_to jogadors_url, notice: 'Jogador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogador
      @jogador = Jogador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jogador_params
      params.require(:jogador).permit(:Nome, :Nick_no_jogo, :user_id, :Idade , :team_ids => [])
    end
end

app/helpers/jogadors_helper.rb
module JogadorsHelper
end

app/views/jogadors/_form.html.erb
<%= bootstrap_form_for(jogador) do |f| %>
  <% if jogador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jogador.errors.count, "erro") %> encontrado: </h2>

      <ul>
      <% jogador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :Nome %>
    <%= f.text_field :Nick_no_jogo %>
    <%= f.number_field :Idade %>
    <%= f.label :Times_Disponíves%>
    <br>
    <%= collection_check_boxes(:jogador ,:team_ids ,Team.where("user_id = "+current_user.id.to_s) ,:id ,:Nome) %>
    <%= f.submit :Confirmar %>
<%end%>

app/views/jogadors/edit.html.erb
<h1>Editing Jogador</h1>

<%= render 'form', jogador: @jogador %>

<%= link_to 'Show', @jogador %> |
<%= link_to 'Back', jogadors_path %>

app/views/jogadors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jogadores</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nick no jogo</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jogadors.each do |jogador| %>
      <tr>
        <td><%= jogador.Nome %></td>
        <td><%= jogador.Nick_no_jogo %></td>
        <td><%= jogador.Idade %></td>
        <td><%= link_to 'Visualizar', jogador %></td>
        <td><%= link_to 'Editar', edit_jogador_path(jogador) %></td>
        <td><%= link_to 'Destruir', jogador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo jogador', new_jogador_path %>

app/views/jogadors/new.html.erb
<h1>Novo jogador</h1>

<%= render 'form', jogador: @jogador %>


<%= link_to 'Back', jogadors_path %>

app/views/jogadors/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @jogador.Nome %>
</p>

<p>
  <strong>Nick no jogo:</strong>
  <%= @jogador.Nick_no_jogo %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @jogador.Idade %>
</p>

<p>
  <strong>Teams:</strong>
    <% @jogador.team.each do |team| %>
      <%= team.Nome %>
    <% end %>
</p>

<%= link_to 'Edit', edit_jogador_path(@jogador) %> |
<%= link_to 'Back', jogadors_path %>