config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'pages#home'
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "home" => "pages#home"
  resources :torneios
  resources :teams
  resources :jogadors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/torneio.rb
class Torneio < ApplicationRecord
  has_and_belongs_to_many :teams
  belongs_to :user
  has_attached_file :cover ,styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/image.png"
  validates_attachment :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_presence_of :Nome, message: "Preenchimento obrigatório"
  validates_uniqueness_of :Nome, message: "já existente"
end

app/controllers/torneios_controller.rb
class TorneiosController < ApplicationController
  before_action :set_torneio, only: [:show, :edit, :update, :destroy]

  # GET /torneios
  # GET /torneios.json
  def index
    @torneios = Torneio.where("user_id = "+current_user.id.to_s)
  end

  # GET /torneios/1
  # GET /torneios/1.json
  def show
  end

  # GET /torneios/new
  def new
    @torneio = Torneio.new
  end

  # GET /torneios/1/edit
  def edit
  end

  # POST /torneios
  # POST /torneios.json
  def create
    @torneio = Torneio.new(torneio_params)
    @torneio.user_id = current_user.id if current_user

    respond_to do |format|
      if @torneio.save
        format.html { redirect_to @torneio, notice: 'Torneio was successfully created.' }
        format.json { render :show, status: :created, location: @torneio }
      else
        format.html { render :new }
        format.json { render json: @torneio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /torneios/1
  # PATCH/PUT /torneios/1.json
  def update
    @torneio.user_id = current_user.id if current_user
    respond_to do |format|
      if @torneio.update(torneio_params)
        format.html { redirect_to @torneio, notice: 'Torneio was successfully updated.' }
        format.json { render :show, status: :ok, location: @torneio }
      else
        format.html { render :edit }
        format.json { render json: @torneio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /torneios/1
  # DELETE /torneios/1.json
  def destroy
    @torneio.destroy
    respond_to do |format|
      format.html { redirect_to torneios_url, notice: 'Torneio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_torneio
      @torneio = Torneio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def torneio_params
      params.require(:torneio).permit(:cover , :user_id, :Nome, :Inicio, :Fim ,:team_ids => [])
    end
end

app/helpers/torneios_helper.rb
module TorneiosHelper
end

app/views/torneios/_form.html.erb
<%= bootstrap_form_for torneio, :html => {multipart: true} do |f| %>
  <% if torneio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(torneio.errors.count, "erro") %> encontrado:</h2>

      <ul>
      <% torneio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>





    <%= f.text_field :Nome %>



    <%= f.date_select :Inicio %>



    <%= f.date_select :Fim %>



    <p> Times disponíveis </p>
    <%= collection_check_boxes(:torneio ,:team_ids ,Team.where("user_id = "+current_user.id.to_s) ,:id ,:Nome) %>




    <%= f.file_field :cover %>

  <br>

    <%= f.submit :Cadastrar%>

<% end %>

app/views/torneios/edit.html.erb
<h1>Editing Torneio</h1>

<%= render 'form', torneio: @torneio %>

<%= link_to 'Show', @torneio %> |
<%= link_to 'Back', torneios_path %>

app/views/torneios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Torneios</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @torneios.each do |torneio| %>
      <tr>
        <td><%= torneio.Nome %></td>
        <td><%= torneio.Inicio %></td>
        <td><%= torneio.Fim %></td>
        <td><%= link_to 'Mostrar', torneio %></td>
        <td><%= link_to 'Editar', edit_torneio_path(torneio) %></td>
        <td><%= link_to 'Destruir', torneio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo torneio', new_torneio_path %>

app/views/torneios/new.html.erb
<h1>Novo torneio</h1>

<%= render 'form', torneio: @torneio %>

<%= link_to 'Back', torneios_path %>

app/views/torneios/show.html.erb
  
<%= image_tag @torneio.cover.url(:thumb) %>

<p>
  <strong>Nome:</strong>
  <%= @torneio.Nome %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @torneio.Inicio %>
</p>

<p>
  <strong>Fim:</strong>
  <%= @torneio.Fim %>
</p>

<p>
  <strong>Times:</strong>
    <% @torneio.teams.each do |team| %>
      <%= team.Nome %>
    <% end %>
</p>