config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'pages#home'
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "home" => "pages#home"
  resources :torneios
  resources :teams
  resources :jogadors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%=home_path%>>EP3 Torneio</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jogador <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Cadastrar novo jogador', new_jogador_path%></li>
            <li></li>
            <li><%= link_to 'Gerenciar jogadores' , jogadors_path%>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li></li>
            <li><%= link_to 'Criar novo time', new_team_path%></li>
            <li><%= link_to 'Gerenciar times', teams_path%></li>


          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Torneio<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Criar novo torneio', new_torneio_path%></li>
            <li><%= link_to 'Gerenciar torneios', torneios_path%></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path  %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
      Logado como <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>